global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-app'
    static_configs:
      - targets: ['api:8080']

  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak:8080']
  
  - job_name: 'database'
    static_configs:
      - targets: ['postgres:5432']
