services:
  api:
    image: ghcr.io/hublot-tech/ln-foot-api:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - lnfoot

  keycloak:
    image: ghcr.io/marcjazz/keycloak-auth-theme:latest
    env_file:
      - .env
    networks:
      - lnfoot
    command:
      - "start"
      - "--import-realm"
      - "--spi-theme-static-max-age=-1"
      - "--spi-theme-cache-themes=false"
      - "--spi-theme-cache-templates=false"
    restart: unless-stopped
    volumes:
      - ./keycloak/config/:/opt/keycloak/data/import/:ro

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - .env
    volumes:
      - minio-data:/data
    networks:
      - lnfoot

  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - lnfoot

volumes:
  pgdata:
  minio-data:

networks:
  lnfoot:
    driver: bridge
