services:
  api:
    image: ghcr.io/hublot-tech/ln-foot-api:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - lnfoot
  
  admin:
    image: ghcr.io/hublots-tech/admin-ln-foot:latest
    restart: unless-stopped
    command: sh -c "npx drizzle-kit migrate && node server.js"
    env_file:
      - "admin/config.env"
    networks:
      - lnfoot

  landing:
    image: ghcr.io/hublots-tech/ln-foot:latest
    restart: unless-stopped
    networks:
      - lnfoot
    environment:
      NODE_ENV: production
      NEXT_API_BASE_URL: https://lnfoot-admin.hublots.co 

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lnfoot

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - lnfoot

  keycloak:
    image: ghcr.io/marcjazz/keycloak-auth-theme:latest
    env_file:
      - "keycloak/config.env"
    networks:
      - lnfoot
    command:
      - "start"
      - "--import-realm"
      - "--spi-theme-static-max-age=-1"
      - "--spi-theme-cache-themes=false"
      - "--spi-theme-cache-templates=false"
    restart: unless-stopped
    volumes:
      - ./keycloak/config/:/opt/keycloak/data/import/:ro

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - "minio/config.env"
    volumes:
      - minio-data:/data
    networks:
      - lnfoot

  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - lnfoot

volumes:
  pgdata:
  minio-data:

networks:
  lnfoot:
    driver: bridge
