services:
  api:
    image: ghcr.io/hublot-tech/ln-foot-api:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - lnfoot
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/api/categories']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - lnfoot

  keycloak:
    image: ghcr.io/marcjazz/keycloak-auth-theme:latest
    env_file:
      - keycloak/.env
    environment:
      - KC_DB_URL_DATABASE=${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - lnfoot
    command:
      - 'start'
      - '--import-realm'
      - '--spi-theme-static-max-age=-1'
      - '--spi-theme-cache-themes=false'
      - '--spi-theme-cache-templates=false'
    restart: unless-stopped
    volumes:
      - ./keycloak/config/:/opt/keycloak/data/import/:ro

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    entrypoint: ['/usr/local/bin/docker-entrypoint.sh']
    restart: unless-stopped
    env_file:
      - minio/.env
    environment:
      APP_CLIENT_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      APP_CLIENT_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/data
      - minio-config:/root/.minio
      - ./minio/entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      # Mount the policy file from your host into the container
      - ./minio/app-client-policy.json:/app_client_policy.json
    networks:
      - lnfoot
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - '80:80'
      - '443:443'
    networks:
      - lnfoot
    healthcheck:
      test: ['CMD', 'curl', '-sSL', 'http://localhost:2019/metrics']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  keycloak-db:
  minio-data:
  minio-config:

networks:
  lnfoot:
    driver: bridge
