apiVersion: v1
kind: Secret
metadata:
  name: api-secret
data:
  MINIO_API_URL: aHR0cDovL21pbmlvLXN2Yzo5MDAw
  DB_HOST: cG9zdGdyZXMtc3Zj
  DB_PORT: NTQzMg==
  KC_ISSUER_URI: aHR0cDovL2tleWNsb2FrLXN2Yzo4MDgwL3JlYWxtcy9sbi1mb290LTAx
  SERVER_URL: aHR0cDovL2xvY2FsaG9zdDo4MDgw
  NOTCHPAY_API_BASE_URL: aHR0cHM6Ly9hcGkubm90Y2hwYXkuY28=
  NOTCHPAY_API_KEY: cGtfdGVzdF9wbGFjZWhvbGRlcg==
  NOTCHPAY_WEBHOOK_SECRET: HNkX3Rlc3RfcGxhY2Vob2xkZXI= # Corrected Base64 for hsk_test_placeholder
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/hublot-tech/ln-foot-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: MINIO_API_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: MINIO_API_URL
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret # Sourced from minio-secret directly
                  key: APP_CLIENT_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret # Sourced from minio-secret directly
                  key: APP_CLIENT_SECRET_KEY
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DB_PORT
            - name: DB_NAME # Sourced from postgres-secret directly
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DB_USERNAME # Sourced from postgres-secret directly
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD # Sourced from postgres-secret directly
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: KC_ISSUER_URI
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: KC_ISSUER_URI
            - name: SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: SERVER_URL
            - name: NOTCHPAY_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: NOTCHPAY_API_BASE_URL
            - name: NOTCHPAY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: NOTCHPAY_API_KEY
            - name: NOTCHPAY_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: NOTCHPAY_WEBHOOK_SECRET
          livenessProbe:
            httpGet:
              path: /api/categories
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5 # Renamed from 'retries'
          readinessProbe:
            httpGet:
              path: /api/categories
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
