apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
# data:
#   realm.json: |
#     { ... realm json ... }
# Note: Consider externalizing this realm JSON into a separate, version-controlled file
# or using a ConfigMap generator for better diffing, versioning, and maintainability,
# especially as the realm configuration grows more complex.
data:
  realm.json: |
    {
      "id": "ln-foot-01",
      "realm": "lnfoot",
      "displayName": "Luvnation Shop",
      "displayNameHtml": "<b>Luvnation Shop</b>",
      "registrationAllowed": true,
      "registrationEmailAsUsername": true,
      "rememberMe": true,
      "loginWithEmailAllowed": true,
      "resetPasswordAllowed": false,
      "enabled": true,
      "supportedLocales": [
        "en",
        "fr"
      ],
      "defaultLocale": "en",
      "internationalizationEnabled": true,
      "defaultRoles": [
        "user"
      ],
      "loginTheme": "ln-foot-01",
      "roles": {
        "realm": [
          {
            "name": "admin",
            "description": "Administrator role with full access"
          },
          {
            "name": "user",
            "description": "Regular user role with limited access"
          },
          {
            "name": "default-roles-lnfoot",
            "composite": true,
            "composites": {
              "realm": [
                "user"
              ]
            },
            "description": "Role automatically assigned to all new users"
          }
        ]
      },
      "identityProviders": [
        {
          "alias": "google",
          "displayName": "Google",
          "providerId": "google",
          "enabled": true,
          "config": {
            "clientId": "google-client-id",
            "clientSecret": "google-client-secret",
            "defaultProvider": true,
            "hideOnLoginPage": false,
            "trustEmail": true,
            "useUserInfoProvider": true,
            "authenticateByDefault": true,
            "defaultRole": "user"
          }
        }
      ],
      "users": [
        {
          "email": "${KC_BOOTSTRAP_ADMIN_USERNAME}",
          "username": "${KC_BOOTSTRAP_ADMIN_USERNAME}",
          "firstName": "LNF Hublots",
          "lastName": "Admin",
          "enabled": true,
          "emailVerified": true,
          "credentials": [
            {
              "temporary": false,
              "type": "password",
              "value": "${KC_BOOTSTRAP_ADMIN_PASSWORD}"
            }
          ],
          "realmRoles": [
            "admin",
            "user"
          ]
        }
      ],
      "clients": [
        {
          "clientId": "ln-foot-01",
          "enabled": true,
          "publicClient": true,
          "redirectUris": [
            "*",
            "com.lnfoot://*"
          ],
          "webOrigins": [
            "*"
          ],
          "protocol": "openid-connect",
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": false,
          "authorizationServicesEnabled": false,
          "fullScopeAllowed": true,
          "attributes": {
            "post.logout.redirect.uris": "+",
            "access.token.lifespan": "3600"
          }
        }
      ]
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
# data:
#   KC_BOOTSTRAP_ADMIN_USERNAME: <base64_encoded_value>
#   KC_BOOTSTRAP_ADMIN_PASSWORD: <base64_encoded_value>
#   KC_HOSTNAME: <base64_encoded_value>
#   KC_LOG_LEVEL: <base64_encoded_value>
#   KC_REALM_NAME: <base64_encoded_value>
#   KC_DB: <base64_encoded_value>
#   KC_HOSTNAME_STRICT: <base64_encoded_value>
#   KC_PROXY: <base64_encoded_value>
#   KC_HTTP_ENABLED: <base64_encoded_value>
#   KC_HTTPS_ENABLED: <base64_encoded_value>
#   KEYCLOAK_PRODUCTION: <base64_encoded_value>
# Note: This Secret should be created manually in the cluster or managed by an external secrets operator.
# Expected keys: KC_BOOTSTRAP_ADMIN_USERNAME, KC_BOOTSTRAP_ADMIN_PASSWORD, KC_HOSTNAME, KC_LOG_LEVEL, KC_REALM_NAME, KC_DB, KC_HOSTNAME_STRICT, KC_PROXY, KC_HTTP_ENABLED, KC_HTTPS_ENABLED, KEYCLOAK_PRODUCTION.
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000 # Common UID for jboss/keycloak user
        runAsGroup: 1000
        fsGroup: 1000
        # seccompProfile: { type: RuntimeDefault }
      initContainers:
        - name: import-realm
          image: busybox
          command: ['sh', '-c', 'cp /config/realm.json /import/realm.json && chmod 644 /import/realm.json']
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true # Busybox can run as non-root for these commands
            runAsUser: 1000    # Using the same as keycloak for consistency
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: realm-config-volume
              mountPath: /config
              readOnly: true
            - name: realm-import-volume
              mountPath: /import
      containers:
        - name: keycloak
          image: ghcr.io/marcjazz/keycloak-auth-theme:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            # readOnlyRootFilesystem: true # Keycloak may write to /opt/jboss or similar paths
          resources:
            requests:
              memory: "256Mi" # Keycloak can be memory intensive
              cpu: "250m"
            limits:
              memory: "1Gi"   # Increased limit for Keycloak
              cpu: "1"        # Increased CPU limit for Keycloak
          # Note: For HA, Keycloak needs clustering configuration & replicas > 1 (possibly StatefulSet).
          startupProbe:
            httpGet:
              # Adjust /auth if Keycloak's context path is different
              path: /auth/realms/master
              port: 8080
            failureThreshold: 60  # 60 * 10s = 600s = 10 minutes
            periodSeconds: 10
          # Liveness and Readiness probes could be added here too, similar to startupProbe
          # or using a different endpoint if available after startup.
          # For now, relying on startupProbe to ensure it eventually starts.
          command:
            - 'start'
            - '--import-realm'
            - '--spi-theme-static-max-age=-1'
            - '--spi-theme-cache-themes=false'
            - '--spi-theme-cache-templates=false'
          ports:
            - containerPort: 8080
          env:
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: KC_DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_BOOTSTRAP_ADMIN_USERNAME
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_BOOTSTRAP_ADMIN_PASSWORD
            - name: KC_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_HOSTNAME
            - name: KC_LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_LOG_LEVEL
            - name: KC_REALM_NAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_REALM_NAME
            - name: KC_DB
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_DB
            - name: KC_HOSTNAME_STRICT
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_HOSTNAME_STRICT
            - name: KC_PROXY
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_PROXY
            - name: KC_HTTP_ENABLED
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_HTTP_ENABLED
            - name: KC_HTTPS_ENABLED
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_HTTPS_ENABLED
            - name: KEYCLOAK_PRODUCTION
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_PRODUCTION
          volumeMounts:
            - name: realm-import-volume
              mountPath: /opt/keycloak/data/import/
      volumes:
        - name: realm-config-volume
          configMap:
            name: keycloak-realm-config
        - name: realm-import-volume
          emptyDir: {}
