name: Deploy Pushed Images to VPS 

on:
  push:
    branches:
      - main
    tags:
      - 'api-*'
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      WORKDIR: ${{ github.repository }}

    permissions:
      packages: read

    steps:
      - name: downcase REPO
        run: |
          echo "WORKDIR=${WORKDIR,,}" >>${GITHUB_ENV}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_SERVER_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/${{ env.WORKDIR }} && cd ~/${{ env.WORKDIR }}
            git pull origin main

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker compose -f docker/compose.prod.yml pull
            docker compose -f docker/compose.prod.yml up -d --remove-orphans
